// <auto-generated />
using System;
using IWEHZ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IWEHZ.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622201313_AddIsPaused")]
    partial class AddIsPaused
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IWEHZ.Domain.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameNl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_nl");

                    b.HasKey("Id");

                    b.HasIndex("NameEn");

                    b.HasIndex("NameNl");

                    b.ToTable("cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            NameEn = "Amsterdam",
                            NameNl = "Amsterdam"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            NameEn = "Rotterdam",
                            NameNl = "Rotterdam"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            NameEn = "The Hague",
                            NameNl = "Den Haag"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            NameEn = "Utrecht",
                            NameNl = "Utrecht"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            NameEn = "Eindhoven",
                            NameNl = "Eindhoven"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            NameEn = "Groningen",
                            NameNl = "Groningen"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            NameEn = "Tilburg",
                            NameNl = "Tilburg"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            NameEn = "Almere",
                            NameNl = "Almere"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            NameEn = "Breda",
                            NameNl = "Breda"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            NameEn = "Nijmegen",
                            NameNl = "Nijmegen"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            NameEn = "Enschede",
                            NameNl = "Enschede"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            NameEn = "Apeldoorn",
                            NameNl = "Apeldoorn"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            NameEn = "Haarlem",
                            NameNl = "Haarlem"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            NameEn = "Arnhem",
                            NameNl = "Arnhem"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            NameEn = "Zaanstad",
                            NameNl = "Zaanstad"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            NameEn = "Amersfoort",
                            NameNl = "Amersfoort"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            NameEn = "Maastricht",
                            NameNl = "Maastricht"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            NameEn = "Dordrecht",
                            NameNl = "Dordrecht"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            NameEn = "Leiden",
                            NameNl = "Leiden"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            NameEn = "Zoetermeer",
                            NameNl = "Zoetermeer"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            NameEn = "Zwolle",
                            NameNl = "Zwolle"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            NameEn = "Deventer",
                            NameNl = "Deventer"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            NameEn = "Delft",
                            NameNl = "Delft"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            NameEn = "Alkmaar",
                            NameNl = "Alkmaar"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            NameEn = "Den Bosch",
                            NameNl = "s-Hertogenbosch"
                        });
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ListingId")
                        .HasColumnType("integer")
                        .HasColumnName("listing_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId", "ListingId")
                        .IsUnique();

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.RentalListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_id");

                    b.Property<decimal?>("PreviousPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("previous_price");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId", "Source")
                        .IsUnique();

                    b.ToTable("rental_listings", (string)null);
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<decimal?>("MaxBudget")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_budget");

                    b.Property<string>("OnboardingState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("onboarding_state");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("text")
                        .HasColumnName("telegram_username");

                    b.HasKey("Id");

                    b.HasIndex("TelegramChatId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.UserCity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.HasKey("UserId", "CityId");

                    b.HasIndex("CityId");

                    b.ToTable("user_cities", (string)null);
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.NotificationLog", b =>
                {
                    b.HasOne("IWEHZ.Domain.Models.RentalListing", "Listing")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IWEHZ.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.UserCity", b =>
                {
                    b.HasOne("IWEHZ.Domain.Models.City", "City")
                        .WithMany("UserCities")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IWEHZ.Domain.Models.User", "User")
                        .WithMany("UserCities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.City", b =>
                {
                    b.Navigation("UserCities");
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.RentalListing", b =>
                {
                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("IWEHZ.Domain.Models.User", b =>
                {
                    b.Navigation("UserCities");
                });
#pragma warning restore 612, 618
        }
    }
}
